/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.ActivityEdge;
import activityecorelua.ActivityNode;
import activityecorelua.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.Activity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityValidator {
	boolean validate();

	boolean validateNodes(EList<ActivityNode> value);
	boolean validateEdges(EList<ActivityEdge> value);
	boolean validateLocals(EList<Variable> value);
	boolean validateInputs(EList<Variable> value);
}
