/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.LastStatement;
import activityecorelua.Statement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.Block}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockValidator {
	boolean validate();

	boolean validateStatements(EList<Statement> value);
	boolean validateReturnValue(LastStatement value);
}
