/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.EDataType;

/**
 * A sample validator interface for {@link activityecorelua.EAttribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EAttributeValidator {
	boolean validate();

	boolean validateID(boolean value);
	boolean validateEAttributeType(EDataType value);
}
