/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.EPackage;
import activityecorelua.ETypeParameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.EClassifier}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EClassifierValidator {
	boolean validate();

	boolean validateInstanceClassName(String value);
	boolean validateInstanceClass(Class<?> value);
	boolean validateDefaultValue(Object value);
	boolean validateInstanceTypeName(String value);
	boolean validateEPackage(EPackage value);
	boolean validateETypeParameters(EList<ETypeParameter> value);
}
