/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.EAttribute;
import activityecorelua.EClass;
import activityecorelua.EGenericType;
import activityecorelua.EOperation;
import activityecorelua.EReference;
import activityecorelua.EStructuralFeature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.EClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EClassValidator {
	boolean validate();

	boolean validateAbstract(boolean value);
	boolean validateInterface(boolean value);
	boolean validateESuperTypes(EList<EClass> value);
	boolean validateEOperations(EList<EOperation> value);
	boolean validateEAllAttributes(EList<EAttribute> value);
	boolean validateEAllReferences(EList<EReference> value);
	boolean validateEReferences(EList<EReference> value);
	boolean validateEAttributes(EList<EAttribute> value);
	boolean validateEAllContainments(EList<EReference> value);
	boolean validateEAllOperations(EList<EOperation> value);
	boolean validateEAllStructuralFeatures(EList<EStructuralFeature> value);
	boolean validateEAllSuperTypes(EList<EClass> value);
	boolean validateEIDAttribute(EAttribute value);
	boolean validateEStructuralFeatures(EList<EStructuralFeature> value);
	boolean validateEGenericSuperTypes(EList<EGenericType> value);
	boolean validateEAllGenericSuperTypes(EList<EGenericType> value);
}
