/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.EEnum;

import org.eclipse.emf.common.util.Enumerator;

/**
 * A sample validator interface for {@link activityecorelua.EEnumLiteral}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EEnumLiteralValidator {
	boolean validate();

	boolean validateValue(int value);
	boolean validateInstance(Enumerator value);
	boolean validateLiteral(String value);
	boolean validateEEnum(EEnum value);
}
