/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.EAnnotation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.EModelElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EModelElementValidator {
	boolean validate();

	boolean validateEAnnotations(EList<EAnnotation> value);
}
