/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.Activity;
import activityecorelua.EClass;
import activityecorelua.EClassifier;
import activityecorelua.EGenericType;
import activityecorelua.EParameter;
import activityecorelua.ETypeParameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.EOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EOperationValidator {
	boolean validate();

	boolean validateEContainingClass(EClass value);
	boolean validateETypeParameters(EList<ETypeParameter> value);
	boolean validateEParameters(EList<EParameter> value);
	boolean validateActivity(Activity value);
	boolean validateEExceptions(EList<EClassifier> value);
	boolean validateEGenericExceptions(EList<EGenericType> value);
}
