/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.EClassifier;
import activityecorelua.EFactory;
import activityecorelua.EPackage;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.EPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EPackageValidator {
	boolean validate();

	boolean validateNsURI(String value);
	boolean validateNsPrefix(String value);
	boolean validateEFactoryInstance(EFactory value);
	boolean validateEClassifiers(EList<EClassifier> value);
	boolean validateESubpackages(EList<EPackage> value);
	boolean validateESuperPackage(EPackage value);
}
