/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.Value;
import activityecorelua.Variable;

/**
 * A sample validator interface for {@link activityecorelua.InputValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputValueValidator {
	boolean validate();

	boolean validateValue(Value value);
	boolean validateVariable(Variable value);
}
