/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.Expression;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.Statement_Assignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Statement_AssignmentValidator {
	boolean validate();

	boolean validateVariable(EList<Expression> value);
	boolean validateValues(EList<Expression> value);
}
