/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.Function;

/**
 * A sample validator interface for {@link activityecorelua.Statement_LocalFunction_Declaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Statement_LocalFunction_DeclarationValidator {
	boolean validate();

	boolean validateFunctionName(String value);
	boolean validateFunction(Function value);
}
