/**
 *
 * $Id$
 */
package activityecorelua.validation;

import activityecorelua.Block;
import activityecorelua.Expression;
import activityecorelua.Statement_If_Then_Else_ElseIfPart;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activityecorelua.Statement_If_Then_Else}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Statement_If_Then_ElseValidator {
	boolean validate();

	boolean validateIfExpression(Expression value);
	boolean validateIfBlock(Block value);
	boolean validateElseIf(EList<Statement_If_Then_Else_ElseIfPart> value);
	boolean validateElseBlock(Block value);
}
